openapi: 3.0.1
info:
  title: Echo
  version: 0.1.0
servers:
- url: "{server}:{port}/echo"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /echo:
    get:
      operationId: getEcho
      parameters:
      - name: message
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    post:
      operationId: postEcho
      parameters:
      - name: message
        in: query
        required: true
        schema:
          type: string
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
